image: ghcr.io/cdce8p/{arch}-base-python
build_from:
  aarch64: "ghcr.io/cdce8p/aarch64-base:"
  armv7: "ghcr.io/cdce8p/armv7-base:"
  armhf: "ghcr.io/cdce8p/armhf-base:"
  amd64: "ghcr.io/cdce8p/amd64-base:"
  i386: "ghcr.io/cdce8p/i386-base:"
cosign:
  base_identity: https://github.com/cdce8p/ha-docker-base/.*
  identity: https://github.com/cdce8p/ha-docker-base/.*
args:
  PYTHON_VERSION: "3.13.7"
  PIP_VERSION: "25.2"
  CERT_IDENTITY: thomas@python.org
  CERT_OIDC_ISSUER: https://accounts.google.com
labels:
  io.hass.base.name: python
  org.opencontainers.image.source: https://github.com/cdce8p/ha-docker-base
